spring:
  messages:
    basename: messages
  data:
    mongodb:
      host: localhost
      port: 27017
      database: athenaeumLibrary
  mongock:
    change-logs-scan-package:
      - ru.otus.spring.changelogs
    enabled: true
    runner-type: InitializingBean

locale: ru
server:
  port: 8089