spring:
  data:
    mongodb:
      host: localhost
      port: 0
      database: athenaeumLibrary
  shell:
    interactive:
      enabled: false
  messages:
    basename: messages
  mongodb:
    embedded:
      version: 4.0.2
  mongock:
    enabled: false